import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const offers = [
  { number: "01", title: "Consulting", tagline: "Bring focus to the work in front of you.", description: "For education leaders navigating change, shaping a new direction, or building alignment around a meaningful goal.", includes: ["Strategic planning and facilitation", "Learning and curriculum strategy", "Team alignment and decision support"] },
  { number: "02", title: "Curriculum Development", tagline: "Build learning that holds together.", description: "For teams ready to create coherent, purposeful curriculum that supports strong teaching and meaningful learning.", includes: ["Scope and sequence development", "Unit and lesson design", "Curriculum review and refinement"] },
  { number: "03", title: "Instructional Design", tagline: "Create experiences that invite people in.", description: "For organizations designing professional learning, learning resources, or instructional experiences with real-world use in mind.", includes: ["Learning experience design", "Facilitator and participant materials", "Engagement and assessment design"] },
];

export default function ServicesPage() {
  return <main className="bg-cream"><section className="relative overflow-hidden bg-ink pb-20 pt-32 text-warmCream"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full border border-sage/30" /><SiteHeader /><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.22em] text-sand">Services</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] tracking-[-0.045em] sm:text-6xl">The right structure can make big ideas <em className="text-sand">move.</em></h1><p className="mt-6 max-w-2xl leading-7 text-warmCream/75">Mind of Najah offers thoughtful partnership for the strategy, curriculum, and learning experiences that move education forward.</p></div></section><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="space-y-5">{offers.map((offer, index) => <article key={offer.title} className="grid gap-8 rounded-3xl border border-ink/10 bg-warmCream p-7 shadow-soft lg:grid-cols-[110px_1fr_0.85fr] lg:p-10"><span className="font-display text-4xl italic text-clay">{offer.number}</span><div><h2 className="font-display text-4xl tracking-[-0.035em]">{offer.title}</h2><p className="mt-3 font-medium text-cobalt">{offer.tagline}</p><p className="mt-4 max-w-xl leading-7 text-ink/70">{offer.description}</p></div><div className="rounded-2xl bg-cream p-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-ink/55">This can include</p><ul className="mt-4 space-y-3">{offer.includes.map((item) => <li key={item} className="flex gap-2 text-sm leading-5 text-ink/75"><Check size={16} className="mt-0.5 shrink-0 text-clay" />{item}</li>)}</ul></div></article>)}</div><div className="mt-16 flex flex-col justify-between gap-6 rounded-3xl bg-sage/55 p-8 md:flex-row md:items-center"><div><p className="eyebrow">Not sure where to begin?</p><p className="mt-2 font-display text-3xl">We can find the right starting point together.</p></div><Button asChild><Link href="/book">Book a consultation <ArrowRight size={16} /></Link></Button></div></section><SiteFooter /></main>;
}
