import Link from "next/link";
import { ArrowRight, Quote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export default function AboutPage() {
  return <main><section className="relative overflow-hidden bg-ink pb-20 pt-32 text-white"><div className="absolute inset-y-0 right-0 w-2/5 bg-sage/15" /><SiteHeader /><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><p className="text-xs font-bold uppercase tracking-[0.22em] text-sand">About Mind of Najah</p><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[1.02] tracking-[-0.045em] sm:text-6xl">Built on the belief that education should feel like a place people can <em className="text-sand">grow.</em></h1></div></section><section className="px-5 py-20 lg:px-8 lg:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.72fr_1.28fr]"><div><p className="eyebrow">A founder-led practice</p><div className="mt-5 aspect-[4/5] rounded-[2rem] bg-sage/65 p-7"><div className="flex h-full items-end rounded-[1.5rem] border border-ink/15 bg-cream p-6"><p className="font-display text-3xl italic leading-tight text-ink/75">Thoughtfulness is not extra. It is part of the work.</p></div></div></div><div className="lg:pt-16"><h2 className="display-title">A partner for the questions behind the project.</h2><div className="mt-7 max-w-2xl space-y-5 leading-7 text-ink/72"><p>Mind of Najah is an independent education consultancy created for the leaders, educators, and organizations doing the careful work of making learning better.</p><p>We believe good education work is both strategic and relational. It has a clear point of view, makes room for context, and gives people something useful to carry forward.</p><p>That is why every partnership begins with attention: to your learners, your team, your values, and the conditions that make meaningful change possible.</p></div><div className="mt-9 rounded-2xl border-l-4 border-clay bg-cream p-6"><Quote size={22} className="text-clay" /><p className="mt-3 font-display text-2xl leading-snug">Clearer purpose. Stronger learning. Work that feels possible to sustain.</p></div></div></div></section><section className="bg-sage/50 px-5 py-20 lg:px-8"><div className="mx-auto max-w-5xl text-center"><p className="eyebrow">Let’s work together</p><h2 className="mt-4 font-display text-4xl tracking-[-0.035em] sm:text-5xl">If the work matters, the way we do it should too.</h2><Button asChild className="mt-8"><Link href="/book">Book a consultation <ArrowRight size={16} /></Link></Button></div></section><SiteFooter /></main>;
}
